#!/bin/bash

TITLE="MINHO HTML1"
CURRENT_TIME=$(date +"%x %r %Z")
TIMESTAMP="Generated $CURRENT_TIME, by $USER"
report_uptime() {
	cat <<- _EOF_
		<H2>System Uptime</H2>
		<PRE>$(uptime)</PRE>
		_EOF_
	return
}

report_disk_space(){
	cat <<- _EOF_
		<H2>Disk Space Utilization</H2>
		<PRE>$(df -h)</PRE>
		_EOF_
	return
}

report_home_space() {
	cat <<- _EOF_
		<H2>Home Space Utilization</H2>
		<PRE>$(du -sh /home/*)</PRE>
		_EOF_
	return
}
cat << _EOF_
<HTML>
	<HEAD>	
		<TITLE>$TITLEM</TITLE>
	</HEAD>
	<BODY>
		<H1>$TITLE</H1>
		<p>$TIMESTAMP</P>
		$(report_uptime)
		$(report_disk_space)
		$(report_home_space)
	</BODY>
</HTML>
_EOF_
